### ISSUE TITLE
py2下发送消息后报错

### ISSUE THREAD

**Issue by zhangqm666** [bluedazzle/wxpy#1]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/miniconda2/lib/python2.7/site-packages/wxpy/api/messages/sent_message.py", line 62, in __repr__
    return Message.__repr__(self)
TypeError: unbound method __repr__() must be called with Message instance as first argument (got SentMessage instance instead)

**Comment by bluedazzle** [comment]
你好，方便提供运行代码吗？
